only reload component if absolutely neccesaray
conorhastings/react-async-branch pull request #3
Opened 2017-08-23 11:26 UTC by conorhastings

@rovolution does this logic look correct?

2017-08-23 14:44 UTC, rovolution requested changes
@conorhastings yea this logic definitely makes sense. no need to check if the `left` or `right` values are different unless the condition corresponds to rendering that component.

only thing was the typo (see code comment)

2017-08-23 14:44 UTC, rovolution commented on src/index.js
> +    (nextProps.condition && nextProps.left !== this.props.condition.left) ||
typo? `this.props.condition.left`-> `this.props.left`?

2017-08-23 15:09 UTC, conorhastings commented on src/index.js
> +    (nextProps.condition && nextProps.left !== this.props.condition.left) ||
👍 nice catch

2017-08-23 21:12 UTC, conorhastings commented
@rovolution updated, look good?

2017-08-23 21:55 UTC, rovolution approved these changes
@conorhastings looks good 👍

2017-08-24 11:04 UTC, merged

2017-08-24 15:24 UTC, rovolution commented
🆒